version: 0.2

env:
  variables:
    SRC_DIR: src/github.com/wrbss/learning-go-echo

phases:
  install:
    commands:
      # install dep
      - go get -u github.com/golang/dep/cmd/dep
      - type dep && dep version
      - echo ${GOPATH}
  pre_build:
    commands:
      # get source and install dependencies
      - mkdir -p ${GOPATH}/${SRC_DIR} && cd ${GOPATH}/${SRC_DIR}
      - mv ${CODEBUILD_SRC_DIR}/* ${CODEBUILD_SRC_DIR}/.??* .
      - dep help
      - dep ensure
  build:
    commands:
      - GOOS=linux GOARCH=amd64 go build -o app app/server.go

artifacts:
  files:
    - app
